DROP TABLE IF EXISTS Genre;
CREATE TABLE Genre(
    ID BIGINT PRIMARY KEY,
    Genre_name VARCHAR(255),
    CONSTRAINT UQ_GenreName UNIQUE (Genre_name)
);

DROP TABLE IF EXISTS Author;
CREATE TABLE Author(
    ID BIGINT PRIMARY KEY,
    Author_name VARCHAR(255)
);

DROP TABLE IF EXISTS Book;
CREATE TABLE Book(
    ID BIGINT PRIMARY KEY,
    Title VARCHAR(255),
    Genre_Id BIGINT NOT NULL,
    Author_Id BIGINT NOT NULL
);

DROP TABLE IF EXISTS Comment;
CREATE TABLE Comment(
    ID BIGINT PRIMARY KEY,
    Comment_Text VARCHAR(255),
    Book_Id BIGINT NOT NULL
);